# Generated by Django 5.0.4 on 2025-09-25 18:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='corrective_type')),
            ],
            options={
                'verbose_name': 'corrective type',
                'verbose_name_plural': 'corrective types',
                'db_table': 'public"."corrective_type',
            },
        ),
        migrations.CreateModel(
            name='DirectionType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='direction_type')),
            ],
            options={
                'verbose_name': 'direction type',
                'verbose_name_plural': 'direction types',
                'db_table': 'public"."direction_type',
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='dronetype')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('drone_type', models.CharField(choices=[('kt', 'kt'), ('st', 'st')], max_length=31, verbose_name='drone_type')),
            ],
            options={
                'verbose_name': 'drone',
                'verbose_name_plural': 'drones',
                'db_table': 'public"."drone',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExplosiveDevice',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='explosive_device')),
            ],
            options={
                'verbose_name': 'explosive device',
                'verbose_name_plural': 'explosive devices',
                'db_table': 'public"."explosive_device',
            },
        ),
        migrations.CreateModel(
            name='ExplosiveType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='explosive_type')),
            ],
            options={
                'verbose_name': 'explosive type',
                'verbose_name_plural': 'explosive types',
                'db_table': 'public"."explosive_type',
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callname', models.CharField(max_length=255, verbose_name='Callname')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='TG ID')),
                ('driver_callname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Driver Callname')),
                ('engineer_callname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Engineer Callname')),
                ('drone_type', models.CharField(blank=True, max_length=127, null=True, verbose_name='Drone Type')),
                ('video_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video Type')),
                ('manual_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manual Type')),
            ],
            options={
                'verbose_name': 'pilot',
                'verbose_name_plural': 'pilots',
                'db_table': 'public"."pilot',
                'ordering': ('callname',),
            },
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='target_type')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='target_value')),
            ],
            options={
                'verbose_name': 'target type',
                'verbose_name_plural': 'target types',
                'db_table': 'public"."target_type',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='flight_number')),
                ('engineer', models.CharField(blank=True, max_length=127, null=True, verbose_name='engineer_callname')),
                ('driver', models.CharField(blank=True, max_length=127, null=True, verbose_name='driver_callname')),
                ('drone', models.CharField(blank=True, max_length=127, null=True, verbose_name='drone_type')),
                ('video', models.CharField(blank=True, max_length=63, null=True, verbose_name='video_type')),
                ('manage', models.CharField(blank=True, max_length=63, null=True, verbose_name='manage_type')),
                ('explosive_type', models.CharField(blank=True, max_length=127, null=True, verbose_name='explosive_type')),
                ('explosive_device', models.CharField(blank=True, max_length=127, null=True, verbose_name='explosive_device')),
                ('flight_date', models.DateField(verbose_name='flight_date')),
                ('flight_time', models.TimeField(verbose_name='flight_time')),
                ('distance', models.CharField(blank=True, max_length=127, null=True, verbose_name='distance')),
                ('video_length', models.CharField(blank=True, max_length=127, null=True, verbose_name='video_length')),
                ('target', models.CharField(blank=True, max_length=127, null=True, verbose_name='target_type')),
                ('corrective', models.CharField(blank=True, max_length=127, null=True, verbose_name='corrective_type')),
                ('result', models.CharField(choices=[('defeated', 'defeated'), ('not defeated', 'not defeated'), ('destroyed', 'destroyed')], default='not defeated', max_length=31, verbose_name='result')),
                ('coordinates', models.CharField(blank=True, max_length=127, null=True, verbose_name='coordinates')),
                ('direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='direction')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='comment')),
                ('drone_remains', models.CharField(blank=True, max_length=255, null=True, verbose_name='drone_remains')),
                ('objective', models.CharField(choices=[('exists', 'exists'), ('not exists', 'not exists')], default='not exists', max_length=31, verbose_name='objective')),
                ('lat_sk42', models.FloatField(blank=True, null=True)),
                ('lon_sk42', models.FloatField(blank=True, null=True)),
                ('lat_wgs84', models.FloatField(blank=True, null=True)),
                ('lon_wgs84', models.FloatField(blank=True, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.pilot', verbose_name='pilot')),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
                'db_table': 'public"."flight',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='flights_users', related_query_name='flights_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='flights_users', related_query_name='flights_user', to='auth.permission', verbose_name='user permissions')),
                ('pilot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='flights.pilot')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
